---
title: "Get_WGS84_Coordinates"
auther: "Jinming LI"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Get_WGS84_Coordinates}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[UTF-8]{inputenc}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## load packages
```{r setup, message = FALSE}
library(getcoords)
require(magrittr)
require(DT)
```

## load example file
```{r example-raw}
set.seed(1234)
file = system.file("extdata", "example_locations.csv", package = "getcoords")
df = utils::read.csv(file = file)
df.new = df %>%
  dplyr::sample_n(size = 60) 
```

## Show example locations
```{r table-raw-data}
DT::datatable(data = df.new, caption = "example locations")
```

## Get the real coordinates(wgs84)
```{r example wgs84}
df.new <- df.new %>% 
  dplyr::mutate(latlon = purrr::map(.x = location, .f = ~geocode(.x))) %>% 
  tidyr::unnest(latlon) %>% 
  dplyr::select(-loc.input)

df.new %>% 
  DT::datatable(data = ., caption = "example locations with WGS84 coordinates")
```

## Plot the points on map with leaflet for activation
```{r map, fig.width=7.3}
library(leaflet)

leaflet() %>% 
  addProviderTiles(provider = providers$OpenStreetMap) %>% 
  addCircleMarkers(data = df.new, 
                   lng = ~lon, 
                   lat = ~lat, 
                   radius = 0.5, 
                   color = "red",
                   popup = ~location
                  )

```
